name: cc-project

services:
  ns_db:
    image: postgres:17.5
    restart: always
    env_file:
     - path: ./city_app/.env
    environment:
      PGPORT: ${NS_PGPORT}
    volumes:
      - ns-data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"

  db_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

  ns_server:
    build:
      context: city_app
    env_file:
      - path: ./city_app/.env
    environment:
      PORT: ${NS_SERVER_PORT}
      CENTRAL_SERVER_PORT: ${CENTRAL_SERVER_PORT}
      PGPORT: ${NS_PGPORT}
      DB_HOST: ${NS_DB_HOST}
    volumes:
      - type: bind
        source: ./city_app/app/
        target: /app
        read_only: true
    ports:
      - "${NS_SERVER_PORT}:${NS_SERVER_PORT}"
    depends_on:
      - ns_db

  central_db:
    image: postgres:17.5
    restart: always
    env_file:
      - path: ./central/.env
    volumes:
      - central-data:/var/lib/postgresql/data

  central_server:
    build:
      context: central
    env_file:
      - path: ./central/.env
    environment:
      PORT: ${CENTRAL_SERVER_PORT}
    volumes:
      - type: bind
        source: ./central/app
        target: /app
        read_only: true
    ports:
      - "${CENTRAL_SERVER_PORT}:${CENTRAL_SERVER_PORT}"
    depends_on:
      - central_db

  su_db:
    image: postgres:17.5
    restart: always
    env_file:
      - path: ./city_app/.env
    environment:
      PGPORT: ${SU_PGPORT}
    volumes:
      - su-data:/var/lib/postgresql/data

  su_server:
    build:
      context: city_app
    env_file:
      - path: ./city_app/.env
    environment:
      PORT: ${SU_SERVER_PORT}
      CENTRAL_SERVER_PORT: ${CENTRAL_SERVER_PORT}
      PGPORT: ${SU_PGPORT}
      DB_HOST: ${SU_DB_HOST}
    volumes:
      - type: bind
        source: ./city_app/app
        target: /app
        read_only: true
    ports:
      - "${SU_SERVER_PORT}:${SU_SERVER_PORT}"
    depends_on:
      - su_db


  kg_db:
    image: postgres:17.5
    restart: always
    env_file:
      - path: ./city_app/.env
    environment:
      PGPORT: ${KG_PGPORT}
    volumes:
      - kg-data:/var/lib/postgresql/data

  kg_server:
    build:
      context: city_app
    env_file:
      - path: ./city_app/.env
    environment:
      PORT: ${KG_SERVER_PORT}
      CENTRAL_SERVER_PORT: ${CENTRAL_SERVER_PORT}
      PGPORT: ${KG_PGPORT}
      DB_HOST: ${KG_DB_HOST}
    volumes:
      - type: bind
        source: ./city_app/app
        target: /app
        read_only: true
    ports:
      - "${KG_SERVER_PORT}:${KG_SERVER_PORT}"
    depends_on:
      - kg_db
volumes:
  ns-data:
  central-data:
  su-data:
  kg-data:
