name: Upload images

on: workflow_dispatch

jobs:
  upload-images:
    name: Upload images
    runs-on: ubuntu-24.04
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Docker login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build central image
        run: docker build ./central -t $DOCKER_USERNAME/cc-central:2
      - name: Build city image
        run: docker build ./city_app -t $DOCKER_USERNAME/cc-city:2
      - name: Push central image
        run: docker push $DOCKER_USERNAME/cc-central:2
      - name: Push city image
        run: docker push $DOCKER_USERNAME/cc-city:2
